"use client"

import { motion } from "framer-motion"
import { GlassCard } from "@/components/dashboard/glass-card"
import { roadmap } from "@/lib/mock-data"
import { Check, MapPin } from "lucide-react"

export function RoadmapSection() {
  return (
    <div className="space-y-6">
      <GlassCard className="p-6">
        <div className="flex items-center gap-2">
          <MapPin className="h-5 w-5 text-primary" />
          <h2 className="text-lg font-semibold">Your 14-Week Personalized Roadmap</h2>
        </div>
        <p className="mt-1 text-sm text-muted-foreground">
          Generated by the Coach Agent from your skill gaps and target companies.
        </p>
      </GlassCard>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        {roadmap.map((phase, i) => (
          <motion.div
            key={phase.phase}
            initial={{ opacity: 0, y: 18 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.08 }}
          >
            <GlassCard className="flex h-full flex-col p-6">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-base font-semibold">{phase.phase}</h3>
                  <p className="text-xs text-muted-foreground">{phase.weeks}</p>
                </div>
                <div className="relative flex h-14 w-14 items-center justify-center">
                  <svg className="h-14 w-14 -rotate-90" viewBox="0 0 56 56">
                    <circle cx="28" cy="28" r="24" fill="none" stroke="var(--secondary)" strokeWidth="5" />
                    <motion.circle
                      cx="28"
                      cy="28"
                      r="24"
                      fill="none"
                      stroke="var(--primary)"
                      strokeWidth="5"
                      strokeLinecap="round"
                      strokeDasharray={2 * Math.PI * 24}
                      initial={{ strokeDashoffset: 2 * Math.PI * 24 }}
                      animate={{ strokeDashoffset: 2 * Math.PI * 24 * (1 - phase.progress / 100) }}
                      transition={{ duration: 1, delay: 0.2 + i * 0.08 }}
                    />
                  </svg>
                  <span className="absolute text-xs font-semibold">{phase.progress}%</span>
                </div>
              </div>
              <ul className="mt-4 space-y-2">
                {phase.items.map((item, j) => {
                  const done = j / phase.items.length < phase.progress / 100
                  return (
                    <li key={item} className="flex items-center gap-2 text-sm">
                      <span
                        className={`flex h-4 w-4 items-center justify-center rounded-full ${
                          done ? "bg-primary text-primary-foreground" : "border border-border"
                        }`}
                      >
                        {done && <Check className="h-3 w-3" />}
                      </span>
                      <span className={done ? "text-foreground" : "text-muted-foreground"}>{item}</span>
                    </li>
                  )
                })}
              </ul>
            </GlassCard>
          </motion.div>
        ))}
      </div>
    </div>
  )
}
