import {
  LayoutDashboard,
  Bot,
  FileText,
  Code2,
  Brain,
  Video,
  Building2,
  Radar,
  Map,
  LineChart,
  Trophy,
  Bell,
  Settings,
  User,
  Users,
  type LucideIcon,
} from 'lucide-react'

export type ViewId =
  | 'dashboard'
  | 'agents'
  | 'resume'
  | 'coding'
  | 'aptitude'
  | 'interview'
  | 'companies'
  | 'skillgap'
  | 'roadmap'
  | 'analytics'
  | 'leaderboard'
  | 'notifications'
  | 'settings'
  | 'profile'
  | 'admin-dashboard'
  | 'admin-users'
  | 'admin-agents'
  | 'admin-settings'

export type NavItem = {
  id: ViewId
  label: string
  icon: LucideIcon
  group: string
  badge?: number
}

export const navItems: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, group: 'Overview' },
  { id: 'agents', label: 'AI Agents', icon: Bot, group: 'Overview' },
  { id: 'resume', label: 'Resume Analyzer', icon: FileText, group: 'Preparation' },
  { id: 'coding', label: 'Coding Arena', icon: Code2, group: 'Preparation' },
  { id: 'aptitude', label: 'Aptitude Lab', icon: Brain, group: 'Preparation' },
  { id: 'interview', label: 'Mock Interview', icon: Video, group: 'Preparation' },
  { id: 'companies', label: 'Company Insights', icon: Building2, group: 'Intelligence' },
  { id: 'skillgap', label: 'Skill Gap Analysis', icon: Radar, group: 'Intelligence' },
  { id: 'roadmap', label: 'Personalized Roadmap', icon: Map, group: 'Intelligence' },
  { id: 'analytics', label: 'Progress Analytics', icon: LineChart, group: 'Intelligence' },
  { id: 'leaderboard', label: 'Leaderboard', icon: Trophy, group: 'Community' },
  { id: 'notifications', label: 'Notifications', icon: Bell, group: 'Community', badge: 4 },
  { id: 'settings', label: 'Settings', icon: Settings, group: 'Account' },
  { id: 'profile', label: 'Profile', icon: User, group: 'Account' },
]

export const adminNavItems: NavItem[] = [
  { id: 'admin-dashboard', label: 'Admin Panel', icon: LayoutDashboard, group: 'Overview' },
  { id: 'admin-users', label: 'User Directory', icon: Users, group: 'Management' },
  { id: 'admin-agents', label: 'Agent Control', icon: Bot, group: 'Management' },
  { id: 'admin-settings', label: 'Site Config', icon: Settings, group: 'Configuration' },
]

export const viewMeta: Record<ViewId, { title: string; subtitle: string }> = {
  dashboard: { title: 'Command Center', subtitle: 'Your AI-orchestrated placement readiness at a glance' },
  agents: { title: 'AI Agents', subtitle: 'Six specialized agents collaborating on your prep' },
  resume: { title: 'Resume Analyzer', subtitle: 'ATS scoring and AI-driven resume optimization' },
  coding: { title: 'Coding Arena', subtitle: 'Practice DSA with an AI pair programmer' },
  aptitude: { title: 'Aptitude Lab', subtitle: 'Adaptive quantitative, logical & verbal drills' },
  interview: { title: 'Mock Interview', subtitle: 'Record, analyze and improve your interviews' },
  companies: { title: 'Company Insights', subtitle: 'Targeted prep timelines for your dream companies' },
  skillgap: { title: 'Skill Gap Analysis', subtitle: 'Where you stand vs. the role you want' },
  roadmap: { title: 'Personalized Roadmap', subtitle: 'An adaptive plan generated by your agents' },
  analytics: { title: 'Progress Analytics', subtitle: 'Trends across every preparation dimension' },
  leaderboard: { title: 'Leaderboard', subtitle: 'See how you rank across the cohort' },
  notifications: { title: 'Notifications', subtitle: 'Agent nudges, deadlines and milestones' },
  settings: { title: 'Settings', subtitle: 'Tune MAPS to how you work' },
  profile: { title: 'Profile', subtitle: 'Your identity across the platform' },
  'admin-dashboard': { title: 'Admin Overview', subtitle: 'Multi-Agent Placement System health and performance analytics' },
  'admin-users': { title: 'Cohort Management', subtitle: 'Monitor students, edit scores, and check streaks' },
  'admin-agents': { title: 'Agent Control Room', subtitle: 'Configure weights, parameters, and active agents' },
  'admin-settings': { title: 'System Settings', subtitle: 'Configure global features and dashboard toggles' },
}
